- .github/workflows/mergify.yml
Only contributors have access to repository secrets.  There isn't a great work around to this so I've disabled the workflow fun if GITHUB_TOKEN is not defined
> fix: handles undefined GITHUB_TOKEN

- typescript/optics-deploy/src/chain.ts
- typescript/optics-deploy/src/deployOptics.ts
- typescript/optics-deploy/src/devDeployOptics.ts
- typescript/optics-tests/lib/index.ts
- typescript/optics-tests/package-lock.json
- typescript/optics-tests/test/common.test.ts
- typescript/optics-tests/test/home.test.ts
- typescript/optics-tests/test/merkle.test.ts
- typescript/optics-tests/test/testChain.ts
- add testChain.ts with utility functions for making test Chain and Deploy
- refactor the Optics hardhat extension
- improve typing of enums in Optics lib
- remove most references to waffle (prefer ethers)
- remove isTestDeploy from deployment args in favor of a test? on Deploys
> refactor: clean up around ts tests

- rust/Cargo.lock
- rust/optics-base/src/agent.rs
- rust/optics-core/src/traits/mod.rs
- rust/optics-ethereum/Cargo.toml
- rust/optics-ethereum/src/macros.rs
- rust/relayer/src/relayer.rs
Adds a timeout to all ethereum txn dispatches. Stops polling the pending txn after 600 seconds to prevent permanent deadlocks in agents.
Related to #455
> feature: time out txns that have been pending confirmation for 10m

- README.md
Committing to `main` requires signed commits; added section so contributors know this is required
> readme: add section about signing commits

- .github/CODEOWNERS
- README.md
> readme: normalize case for optics-xapps dir, add self as rust codeowner

- solidity/optics-core/contracts/Home.sol
This is probably pedantic, but IMO the comment was misleading as it seemed to imply that only the updater calls this function. Instead, in the fraud case, anyone can and should submit the invalid root that was signed to cause slashing. Though I can't claim that my proposed changes are much more clear, so feel free to adjust
> Clarify Home#update notice

- rust/kathy/src/main.rs
- rust/optics-base/bin/example.rs
- rust/optics-base/src/settings/trace/jaeger.rs
- rust/optics-base/src/settings/trace/mod.rs
- rust/optics-base/src/settings/trace/zipkin.rs
- rust/processor/src/main.rs
- rust/relayer/src/main.rs
- rust/updater/src/main.rs
- rust/watcher/src/main.rs
mainly just looks nicer to read by avoiding a bunch of std::convert boilerplate.
> refactor: fewer trait impls in tracing setup

- .github/workflows/solidity.yml
- pre-commit.sh
- scripts/resolve-typechain-conflicts.sh
- scripts/test-all.sh
- scripts/test-solditity.sh
- scripts/test-solidity.sh
- solidity/optics-core/package.json
- solidity/optics-core/test.sh
- solidity/optics-xapps/package.json
- typescript/optics-tests/package-lock.json
- typescript/optics-tests/package.json
Closes #582 
- All solidity tests are run at the same time, updated test scripts to reflect that
- Refactors GitHub actions
- `optics-tests`'s `test` script now compile solidity before running
- Adds `testNoCompile` script in `optics-test` for utility
> refactor: update test scripts

- .github/workflows/solidity.yml
I know it's verbose, but it will save us time on checks
> refactor: split cache, install independently

- rust/Cargo.lock
- rust/optics-core/Cargo.toml
Ethers put websocket support under a feature flag in the 0.5 release family. We explicitly enable that flag here
if you encounter issues, run `cargo update` before compiling
> chore: add explicit ws dep to work with new ethers

- typescript/optics-deploy/src/bridge/BridgeDeploy.ts
- typescript/optics-deploy/src/chain.ts
- typescript/optics-deploy/src/core/CoreContracts.ts
- typescript/optics-deploy/src/core/CoreDeploy.ts
- typescript/optics-deploy/src/core/index.ts
- typescript/optics-tests/package-lock.json
1. adds a configuration option and method to transfer the root governorship of the governing chain's governance router on deployment
2. improves the deployment contract output to include other relevant addresses
> bug: transfer root governorship to configured governor on gov chain

- rust/agents/processor/src/prover_sync.rs
removes a rate limiter from prover_sync
Note that on an initial sync this may blow out request limits on API.  see #685
> bug: remove ancient debug rate limiter in prover_sync

- README.md
- docs/faq.md
There was inconsistency with how we were casing 'xApp'. Unless there is a filename or naming convention e.g. `XAppConnectionManager` or `solidity/optics-xapps`, the lower case 'x', uppercase 'A' is used.
> docs: make casing consistent for usage of 'xApp' in README

- rust/agents/updater/src/updater.rs
- change behavior of poller when queue is full to drop updates
- change queue length to 1
- add a pre-wait check in the update handler's handle function
CC @nambrot thanks :)
> refactor: update poller loop behavior to reduce latency

- rust/agents/processor/src/processor.rs
- rust/agents/updater/src/updater.rs
- rust/optics-base/src/metrics.rs
privated the metrics registry and added official interface for setting up per-replica metrics
> bug: metrics no longer panics when attempting to register multiple replicas

- docs/xapps/token-bridge.md
Message tracing comes up pretty often when explaining the system. This should hopefully clarify the pattern and how to pseudo-trace.
> docs: adds information about message tracing in token-bridge.md

- rust/agents/processor/src/processor.rs
- rust/agents/processor/src/prover.rs
- rust/agents/processor/src/prover_sync.rs
- rust/chains/optics-ethereum/src/macros.rs
- rust/optics-core/src/db/mod.rs
- There was a significant bug where `from_disk` would cause `incremental` and `prover` to have different states
- while fixing this, I did some significant refactors to prover sync to have it rely on HomeIndexer and not block
- also made it run a proof-presence check on startup to ensure that we don't somehow miss proofs
- To consider: ProverSync no longer makes RPC requests so it is 100% sync now. What's a reasonable way (besides `wait_for_leaf`) to make it yield priority to other tasks?
> bug: ProverSync from_disk now properly recovers tree state, proofs, etc.

- rust/agents/processor/src/prover_sync.rs
- rust/agents/updater/src/updater.rs
- rust/agents/watcher/src/watcher.rs
- rust/chains/optics-ethereum/src/home.rs
- rust/optics-core/src/db/home_db.rs
- Orders queried update events by `blocknumber` and `transaction_index` within block (should solve skipped messages issue?)
- Stop proversync leaf/proof check at `prover.count()` (don't try to build proofs for leaves without an update yet)
- Adds `warn!` when we attempt to store root that doesn't build off latest root (shouldn't happen anymore though after fix)
Potentially related to #812
> fix: fix potential out-of-order updates when `HomeIndexer` syncing

- rust/agents/processor/src/processor.rs
- rust/agents/processor/src/settings.rs
Adds a `sync` config param. Setting this param to any string value will put the processor in sync-only mode. The processor will not dispatch txns to replicas, it will only sync the DB.
> feature: optionally skip replica tasks

- rust/agents/processor/src/processor.rs
- rust/chains/optics-ethereum/src/home.rs
- rust/optics-core/src/db/home_db.rs
- rust/optics-core/src/db/typed_db.rs
- rust/optics-core/src/traits/home.rs
- rust/optics-test/src/test_utils.rs
- rust/tools/prove-cli/src/main.rs
Bug: multiple `Replica` processors were sharing the same key for storing their latest inspected nonces
Changes:
-  key latest nonces by replica domain
- improve docs for pub db store functions
- Processor `IntGaugeVec` tracks Replica processor next_nonces
- standardize on `leaf` and remove all refs to `leaf_hash`
Closes #851
> fix: fix processor index/nonce conflation and add per-replica nonce storage

- tools/keymaster/keymaster.py
Only top-up wallets that _really_ need to be topped up.
> fix: keymaster use explicit lower bound

- rust/agents/kathy/src/kathy.rs
- add lock to kathy and have her acquire and hold for duration of `home.dispatch(...).await` calls to ensure only one dispatch call happening at one time (temp fix to ether-rs concurrency bug)
- lock does not wrap home because that would require changing `AgentCore` setup
Closes #857
> fix: fix kathy sync bug related to `ethers-rs` concurrency

- rust/chains/optics-ethereum/src/home.rs
- rust/optics-core/src/db/home_db.rs
- rust/optics-core/src/types/update.rs
- home indexer stores `UpdateMeta` struct in db (keyed by `update.new_root`)
- `UpdateMeta` currently only has `block_number` but we can add any additional fields if needed
Closes #822
> feature: `HomeIndexer` stores update metadata

- rust/Cargo.lock
- rust/agents/processor/src/processor.rs
- rust/agents/relayer/Cargo.toml
- rust/agents/relayer/src/relayer.rs
- rust/agents/updater/src/submit.rs
- rust/agents/updater/src/updater.rs
- rust/optics-core/src/db/optics_db.rs
Bad dependency but running this in prod is contingent on testing previous [updater PR](https://github.com/celo-org/optics-monorepo/pull/909) in dev first...
For #917
> feature: add metrics/tracking to remaining agents

- solidity/optics-core/package-lock.json
- solidity/optics-core/package.json
- solidity/optics-xapps/contracts/Router.sol
- solidity/optics-xapps/contracts/XAppConnectionClient.sol
- solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
- solidity/optics-xapps/contracts/bridge/BridgeToken.sol
- solidity/optics-xapps/contracts/bridge/ETHHelper.sol
- solidity/optics-xapps/contracts/bridge/TokenRegistry.sol
- solidity/optics-xapps/contracts/bridge/test/MockCore.sol
- solidity/optics-xapps/package-lock.json
- solidity/optics-xapps/package.json
Even those these packages aren't published we're switching them to use the correct npm organization in case someone were to actually publish something malicious to the npm registry using these names.
> Switch packages to use the correct npm org
