abis/Home.abi.json, abis/Replica.abi.json, solidity/optics-core/contracts/Common.sol, solidity/optics-core/contracts/Home.sol, solidity/optics-core/contracts/Replica.sol, solidity/optics-core/contracts/test/TestCommon.sol, solidity/optics-core/test/Common.test.js, solidity/optics-core/test/Replica.test.js
Removes the initializer from Common. Makes misc. type changes to Home functions to support this
=> bug: disable external common initializer

.github/CODEOWNERS
Out on my own terms 😢😂
Closes #379
=> Remove Luke as codeowner

.gitignore, rust/config/1622504632050-alfajores-goerli/alfajores_config.json, rust/config/1622504632050-alfajores-goerli/goerli_config.json, rust/config/1622591031448-alfajores-goerli/alfajores_config.json, rust/config/1622591031448-alfajores-goerli/goerli_config.json, rust/config/alfa-goerli/alfa_config.json, rust/config/alfa-goerli/goerli_config.json, rust/config/default/base.json, rust/optics-base/src/settings/chains.rs, rust/optics-base/src/settings/mod.rs, rust/optics-ethereum/src/lib.rs, rust/optics-ethereum/src/settings.rs, rust/updater/src/settings.rs, rust/watcher/src/settings.rs, rust/watcher/src/watcher.rs, typescript/src/chain.ts
@ErinHales please note the config changes as they affect the TS work
=> refactor: break signers out of replicas in rust configs

typescript/src/chain.ts, typescript/src/index.ts, typescript/src/proxyUtils.ts
=> enhance: typescript deploy process

pre-commit.sh, solidity/optics-core/package.json, solidity/optics-xapps/package.json
=> chore: add typechain generation to standard pre-commit script

solidity/optics-core/contracts/Home.sol, solidity/optics-core/test/Home.test.js, solidity/optics-core/test/cross-chain/GovernanceRouter.test.js, solidity/optics-core/test/cross-chain/generateTestChainConfigs.js
@ErinHales can you fix the last test on this? The cross-chain governance proof needs to be regenerated. cc @anna-carroll if you get stuck
closes #396
=> refactor: home 0-indexes sequences

rust/config/1622591031448-alfajores-goerli/kathy-partial.json, rust/config/1622591031448-alfajores-goerli/processor-partial.json, rust/config/1622591031448-alfajores-goerli/relayer-partial.json, rust/config/1622591031448-alfajores-goerli/updater-partial.json
Add partial configs to testnet deploy accidentally pushed to main
=> Add partial configs

typescript/src/index.ts
=> Copy partial configs during deploy script

typescript/optics-deploy/src/deployOptics.ts, typescript/optics-tests/lib/index.ts, typescript/optics-tests/lib/types.ts, typescript/optics-tests/test/cross-chain/simpleMessage.test.ts, typescript/optics-tests/test/cross-chain/utils.ts, typescript/optics-tests/test/home.test.ts
- Add return types
- Fix GovernanceMessage enum error
- Add SimpleMessage tests in ts
=> test: SimpleMessage ts

typescript/optics-deploy/src/deployOptics.ts, typescript/optics-tests/test/cross-chain/governanceRouter.test.ts, typescript/optics-tests/test/cross-chain/simpleMessage.test.ts, typescript/optics-tests/test/testChain.ts, typescript/optics-tests/test/upgrade.test.ts, typescript/optics-tests/test/upgradeUtils.ts, typescript/optics-tests/test/utils.ts, typescript/optics-tests/test/xAppConnectionManager.test.ts
=> WIP: test: governance router/upgrade ts

resolve-typechain-conflicts.sh
Adds script to resolve typechain conflicts during rebase
=> add: resolve-typechain-conflicts script

typescript/optics-tests/test/replica.test.ts
=> test: add replica test case of processing message sent to a non-existent contract address

resolve-typechain-conflicts.sh
- Corrected filepath to `typescript/typechain
- Changed to `git rm -rf`
=> fix: resolve-typechain-conflicts.sh

solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
=> Do not deploy token on details message

rust/provision_kms_keys.py
Example output from dev account: 
```
╒══════════════════════════════════════╤═══════════╤══════════════════════════════════════╤═════════════════════════════════════════════════════════════════════════════╤════════════════════════════════╤════════════════════════════════════════════╕
│ Alias Name                           │ Region    │ Key ID                               │ ARN                                                                         │ Key Description                │ Ethereum Address                           │
╞══════════════════════════════════════╪═══════════╪══════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════╪════════════════════════════════╪════════════════════════════════════════════╡
│ …
```
=> [Feature] Added provisioning script for KMS keys

typescript/optics-deploy/config/alfajores.ts, typescript/optics-deploy/config/kovan.ts, typescript/optics-deploy/scripts/alfajoresKovan.ts, typescript/optics-deploy/src/chain.ts, typescript/optics-deploy/src/core/CoreDeploy.ts, typescript/optics-tests/test/testChain.ts
- Add a dev/staging/prod configuration variable to core configs
- Add an environment variable we can set to choose between them
=> feature: deploy core can distinguish between dev/prod/staging

rust/helm/optics-agent/Chart.yaml, rust/helm/optics-agent/templates/_helpers.tpl, rust/helm/optics-agent/templates/configmap.yaml, rust/helm/optics-agent/templates/kathy-statefulset.yaml, rust/helm/optics-agent/templates/processor-statefulset.yaml, rust/helm/optics-agent/templates/relayer-statefulset.yaml, rust/helm/optics-agent/templates/serviceaccount.yaml, rust/helm/optics-agent/templates/updater-statefulset.yaml, rust/helm/optics-agent/values.yaml
This updates the Helm chart with a few extra params and simplifies some of the common configuration
* Updated to use dedicated resources and pod lables/annotations
* Added ConfigMap for common envs
* Updated storage configuration to be more flexible
* Added missing envs for db path, backtrace and loggings
=> Helm Chart Update

rust/agents/kathy/src/kathy.rs, rust/agents/processor/src/main.rs, rust/agents/processor/src/processor.rs, rust/optics-base/src/agent.rs, rust/optics-base/src/home.rs, rust/optics-base/src/macros.rs, rust/optics-base/src/replica.rs, rust/optics-core/src/traits/encode.rs, rust/optics-core/src/traits/home.rs, rust/optics-core/src/types/update.rs, rust/optics-test/src/mocks/replica.rs
currently working on:
1. reducing the number of events (lots of extraneous ones?)
2. increasing the number of spans
3. making sure the relations between them make sense
4. adding fields + structured metadata connecting disparate things, esp loading up spans with all the metadata events later reference
5. instrumenting optics-base
Closes #580 #631
=> refactor processor to have nicer behavioural traces

rust/helm/optics-agent/templates/configmap.yaml, rust/helm/optics-agent/templates/kathy-statefulset.yaml, rust/helm/optics-agent/templates/processor-statefulset.yaml, rust/helm/optics-agent/templates/relayer-statefulset.yaml, rust/helm/optics-agent/templates/updater-statefulset.yaml, rust/helm/optics-agent/values.yaml
* Fixes agent persistence across reboots and upgrades _(yahoo!)_
=> fix: fixed podSecurityContext in helm chart

rust/agents/processor/src/prover_sync.rs
adding some logging to help diagnose slow tree rebuilding
=> feature: add span and debugs to fetch_leaf

typescript/optics-deploy/src/chain.ts, typescript/optics-deploy/src/core/index.ts, typescript/optics-deploy/src/deploy.ts
some deployment in n-chain stuff relied on governed actions after relinquishing
=> fixing n-chain deploy tx ordering

rust/agents/kathy/src/kathy.rs, rust/agents/kathy/src/settings.rs, rust/agents/processor/src/processor.rs, rust/agents/processor/src/settings.rs, rust/agents/relayer/src/relayer.rs, rust/agents/relayer/src/settings.rs, rust/agents/updater/src/settings.rs, rust/agents/updater/src/updater.rs, rust/agents/watcher/src/settings.rs, rust/agents/watcher/src/watcher.rs, rust/config/1629741887167/kathy-partial.json, rust/config/1629741887167/processor-partial.json, rust/config/1629741887167/relayer-partial.json, rust/config/1629741887167/updater-partial.json, rust/config/1629741887167/watcher-partial.json, rust/config/1629743021549/kathy-partial.json, rust/config/1629743021549/processor-partial.json, rust/config/1629743021549/relayer-partial.json, rust/config/1629743021549/updater-partial.json, rust/config/1629743021549/watcher-partial.json, rust/config/1630513764971/kathy-partial.json, rust/config/1630513764971/processor-partial.json, rust/config/1630513764971/relayer-partial.json, rust/config/1630513764971/updater-partial.json, rust/config/1630513764971/watcher-partial.json, rust/helm/optics-agent/templates/kathy-statefulset.yaml, rust/helm/optics-agent/templates/processor-statefulset.yaml, rust/helm/optics-agent/templates/relayer-statefulset.yaml, rust/helm/optics-agent/templates/updater-statefulset.yaml
renames config vars for easier env setting
=> refactor: polling_interval -> interval, updater_pause -> pause

rust/Cargo.lock, rust/agents/kathy/src/kathy.rs, rust/agents/kathy/src/main.rs, rust/agents/processor/Cargo.toml, rust/agents/processor/src/main.rs, rust/agents/processor/src/processor.rs, rust/agents/relayer/src/main.rs, rust/agents/relayer/src/relayer.rs, rust/agents/updater/Cargo.toml, rust/agents/updater/src/main.rs, rust/agents/updater/src/updater.rs, rust/agents/watcher/Cargo.toml, rust/agents/watcher/src/main.rs, rust/agents/watcher/src/watcher.rs, rust/config/default/base.json, rust/optics-base/Cargo.toml, rust/optics-base/src/agent.rs, rust/optics-base/src/lib.rs, rust/optics-base/src/metrics.rs, rust/optics-base/src/settings/mod.rs
=> rust agents: expose prometheus metrics

typescript/optics-deploy/src/chain.ts, typescript/optics-deploy/src/core/CoreDeploy.ts
=> feature: do not output rpc url in deploy output

rust/agents/kathy/src/kathy.rs
by request of @yourbuddyconner
=> refactor: make kathy sleep at top of loop

tools/keymaster/README.md, tools/keymaster/config.py, tools/keymaster/keymaster-example.json, tools/keymaster/keymaster.py, tools/keymaster/requirements.txt, tools/keymaster/utils.py
=> feature: The Keymaster

rust/Cargo.lock, rust/agents/processor/src/processor.rs, rust/agents/updater/src/updater.rs, rust/chains/optics-ethereum/Cargo.toml, rust/chains/optics-ethereum/src/settings.rs, rust/optics-base/src/metrics.rs, rust/optics-base/src/settings/chains.rs, rust/optics-base/src/settings/mod.rs
Cleans up some existing metrics, using labels for dimensioning.
Closes #719 #723 #718
=> feature: additional agent metrics

rust/config/1630962358898/alfajores_verification.json, rust/config/1630962358898/bridge/1631040934249/alfajores_verification.json, rust/config/1630962358898/bridge/1631040934249/kovan_verification.json, rust/config/1630962358898/bridge/1631040934249/rinkeby_verification.json, rust/config/1630962358898/kovan_verification.json, rust/config/1630962358898/rinkeby_verification.json, rust/config/1631125589812/alfajores_verification.json, rust/config/1631125589812/bridge/1631126158135/alfajores_verification.json, rust/config/1631125589812/bridge/1631126158135/kovan_verification.json, rust/config/1631125589812/bridge/1631126158135/rinkeby_verification.json, rust/config/1631125589812/kovan_verification.json, rust/config/1631125589812/rinkeby_verification.json, rust/config/mainnet/bridge/1631143085018/celo_verification.json, rust/config/mainnet/bridge/1631143085018/ethereum_verification.json, rust/config/mainnet/bridge/1631143085018/polygon_verification.json, rust/config/mainnet/celo_verification.json, rust/config/mainnet/ethereum_verification.json, rust/config/mainnet/polygon_verification.json, typescript/optics-deploy/src/bridge/checks.ts, typescript/optics-deploy/src/bridge/index.ts, typescript/optics-deploy/src/core/checks.ts, typescript/optics-deploy/src/core/index.ts, typescript/optics-deploy/src/deploy.ts, typescript/optics-deploy/src/proxyUtils.ts, typescript/optics-deploy/src/verification/readDeployOutput.ts, typescript/optics-tests/test/cross-chain/governanceRouter.test.ts, typescript/optics-tests/test/deploy.test.ts
Closes #740 
- fixes contract verification names
- checks verification output
- checks replicas use common implementation/beacon
=> enhancement: check verification

rust/Cargo.lock, rust/Cargo.toml, rust/Dockerfile, rust/agents/kathy/src/main.rs, rust/agents/processor/src/main.rs, rust/agents/processor/src/processor.rs, rust/agents/processor/src/prover_sync.rs, rust/agents/relayer/src/main.rs, rust/agents/updater/src/main.rs, rust/chains/optics-ethereum/src/settings.rs, rust/optics-base/bin/example.rs, rust/optics-base/src/agent.rs
Behavior is correct locally
Note that this disables the Watcher in Cargo.toml, pending #782
=> Prover sync refactoring

docs/xapps/token-bridge.md
=> docs: fix typo 'bridge'

rust/agents/kathy/src/main.rs, rust/agents/processor/src/main.rs, rust/agents/relayer/src/main.rs, rust/agents/updater/src/main.rs, rust/agents/watcher/src/main.rs, rust/agents/watcher/src/watcher.rs, rust/chains/optics-ethereum/src/settings.rs, rust/optics-base/bin/example.rs, rust/optics-base/src/agent.rs, rust/optics-base/src/metrics.rs, rust/optics-base/src/settings/chains.rs, rust/optics-base/src/settings/mod.rs, rust/optics-base/src/settings/trace/mod.rs, rust/optics-base/src/settings/trace/span_metrics.rs
this isn't quite #770, but it is probably a lot of metric.
=> feature: record span durations as a metric

rust/optics-base/src/metrics.rs
=> metrics 404 message

typescript/optics-provider/.eslintignore, typescript/optics-provider/.eslintrc.json, typescript/optics-provider/package-lock.json, typescript/optics-provider/package.json, typescript/optics-provider/src/contracts.ts, typescript/optics-provider/src/metamask.ts, typescript/optics-provider/src/optics/OpticsContext.ts, typescript/optics-provider/src/optics/contracts/BridgeContracts.ts, typescript/optics-provider/src/optics/contracts/CoreContracts.ts, typescript/optics-provider/src/optics/events/bridgeEvents.ts, typescript/optics-provider/src/optics/events/fetch.ts, typescript/optics-provider/src/optics/events/index.ts, typescript/optics-provider/src/optics/events/opticsEvents.ts, typescript/optics-provider/src/optics/index.ts, typescript/optics-provider/src/optics/messages/BridgeMessage.ts, typescript/optics-provider/src/optics/messages/OpticsMessage.ts, typescript/optics-provider/src/provider.ts
Make Annotated a class so we can have a bunch of nice getters and stuff :)
=> refactor: Annotated is now a proper class

.gitignore, rust/Cargo.lock, rust/agents/processor/Cargo.toml, rust/agents/processor/src/main.rs, rust/agents/processor/src/processor.rs, rust/agents/processor/src/push.rs, rust/agents/processor/src/settings.rs, rust/optics-base/src/agent.rs
Closes #811 
@yourbuddyconner please set up a bucket where we can test this.
@ltchang2019 please review code
=> feature: configuration to push proofs to s3 buckets

typescript/contract-metrics/package-lock.json, typescript/contract-metrics/package.json, typescript/contract-metrics/src/config.ts, typescript/contract-metrics/src/gas.ts, typescript/contract-metrics/src/monitor.ts, typescript/contract-metrics/src/print.ts, typescript/contract-metrics/src/registerContext.ts, typescript/contract-metrics/src/tokens.ts, typescript/contract-metrics/src/trace.ts, typescript/optics-provider/src/optics/domains/mainnetCommunity.ts
- Bumps the provider package to paginate Avalanche RPC event lookups
- Updates the `contracts-metrics` package to observe the v2 deployment
=> Update contracts-metrics for productionCommunity
